### ISSUE TITLE
师兄你好

### ISSUE THREAD

**Issue by Steve0x2a** [Jacen789/GzhuGradesCrawler#1]
因为自己也在写相关项目 在谷歌上搜索到了您的项目
在阅读您的源码时 发现在[此处](https://github.com/Jacen789/GzhuGradesCrawler/blob/master/GzhuGradesCrawler3/grades_crawler.py)的十三行有师兄您的教务系统学号以及密码
不知道是师兄忘记删去还是觉得无所谓呢 提醒一下
以及有些问题希望可以和师兄探讨一下

**Comment by Jacen789** [comment]
谢谢提醒，已回退删除敏感信息。原谅我这么晚才看到。
